### ISSUE TITLE
New docs pages required for Vx675 and Vx680

### ISSUE THREAD

**Issue by davidtkelleher** [cloudwalkio/cloudwalk-docs#26]
A new documentation page is required to explain and illustrate the process of installing the WALK Framework on terminals Verifone Vx675 and Vx685.

This page should exist as a link from https://docs.cloudwalk.io/en/walk-framework/verifone-evo
and in the same format as the existing link:
"To load the framework on terminals VX 805 and VX 820, check out this guide."

**Comment by tunnelshade** [comment]
Hey, can you just tell the keys to press for Vx675 to open terminal manager

**Comment by gabrielbernal** [comment]
Enhancement done on the branch tech_review
