### ISSUE TITLE
Make the documentation for the mruby workflow.

### ISSUE THREAD

**Issue by sadasant** [cloudwalkio/cloudwalk-docs#6]
Hey @bmsatierf :D 

I want to help you to extend this project to include the documentation of mruby apps.

Right now I'm trying the behavior of the POS module in the browser and I'll be making example codes to try all the functions, I think it would be useful to start using those examples as part of a sketch of the mruby workflow documentation. What do you think? I can open a new branch for that! :)

**Comment by gabrielbernal** [comment]
https://trello.com/c/Zks3OxNl/10-atualizar-documentacao checklist: Misc
