### ISSUE TITLE
The variablereturn from filesystem.renamefile need to change for integer

### ISSUE THREAD

**Issue by lucascastejon** [cloudwalkio/cloudwalk-docs#83]
Link: https://docs.cloudwalk.io/en/posxml/commands/filesystem.renamefile

Can you see more on attach.

Thank you

![ch1wt3t](https://cloud.githubusercontent.com/assets/4714691/12330663/6f2188b8-bacd-11e5-8bad-4a892bed6c0f.png)

**Comment by scalone** [comment]
It really returns a integer
https://github.com/planobe/walk_framework/blob/master/src/pos/application/walk.c#L3171


--

Thiago Scalone
+55 16 992-410-585
@scalone
