### ISSUE TITLE
Incorrect word on time.calculate documentation - error: Concert. correct: Convert

### ISSUE THREAD

**Issue by lucascastejon** [cloudwalkio/cloudwalk-docs#88]
On the example need to change the word Concert to Convert.

Link: https://docs.cloudwalk.io/en/posxml/commands/time.calculate

Look the screenshot: 
![time calculate](https://cloud.githubusercontent.com/assets/4714691/12392686/e9c56ed8-bdd7-11e5-8fc8-d200f869e907.png)

**Comment by gabrielbernal** [comment]
updated: https://gist.github.com/posxml/fb217565330e1c97044b
