### ISSUE TITLE
Change "Retorno" word from Portuguese to English

### ISSUE THREAD

**Issue by lucascastejon** [cloudwalkio/cloudwalk-docs#89]
Link: https://docs.cloudwalk.io/en/posxml/commands/string.fromhex

![stringfromhex](https://cloud.githubusercontent.com/assets/4714691/12397979/dc366a40-bdf7-11e5-9fcb-45fc678969b7.png)

**Comment by gabrielbernal** [comment]
done. https://gist.github.com/posxml/6fa9fe97d7739c6bcc48
