### ISSUE TITLE
Need to get a header on **smartcard.insetedcard** command

### ISSUE THREAD

**Issue by lucascastejon** [cloudwalkio/cloudwalk-docs#90]
Link: https://docs.cloudwalk.io/en/posxml/commands/smartcard.insertedcard

Man @williamrgt can you help me with header this command ?

And @davidtkelleher after get the header, need to change "principal"  word from portuguese to english.
(you can see below) 

Example header(open these commands)
- [smartcard.closereader](https://docs.cloudwalk.io/en/posxml/commands/smartcard.closereader)
- [smartcard.startreader](https://docs.cloudwalk.io/en/posxml/commands/smartcard.startreader)
- [smartcard.transmitapdu](https://docs.cloudwalk.io/en/posxml/commands/smartcard.transmitapdu)

Look the screenshot:
![smartcard](https://cloud.githubusercontent.com/assets/4714691/12398290/d6a9581a-bdf9-11e5-9525-68c07f075934.png)

**Comment by gabrielbernal** [comment]
done. https://github.com/cloudwalkio/cloudwalk-docs/commit/fceb7bb54c54652819950273c1b1bd02d776b168
