### ISSUE TITLE
Remove caracter invalid in the example "smartcard.startreader" command

### ISSUE THREAD

**Issue by lucascastejon** [cloudwalkio/cloudwalk-docs#91]
On comment the command [smartcard.startreader](https://docs.cloudwalk.io/en/posxml/commands/smartcard.startreader)  need to remove a caracter "<" invalid.

Can you seen on scheenshot: 
![smartstarter](https://cloud.githubusercontent.com/assets/4714691/12480217/d1abdf10-c027-11e5-9dad-7577cd8cc81a.png)

**Comment by gabrielbernal** [comment]
updated: https://gist.github.com/posxml/a48b1ea7fb87ed557638
