### ISSUE TITLE
The documentation of **iso8583.transactmessage** have a duplicate party.

### ISSUE THREAD

**Issue by lucascastejon** [cloudwalkio/cloudwalk-docs#92]
Link: https://docs.cloudwalk.io/en/posxml/commands/iso8583.transactmessage

See more:
![iso8583transactimessage](https://cloud.githubusercontent.com/assets/4714691/12489960/2f94c042-c05a-11e5-8779-4b83878648a4.png)

**Comment by gabrielbernal** [comment]
fixed: https://github.com/cloudwalkio/cloudwalk-docs/commit/0ecc3fdaa2c3e5fbae91cb1f7ad8ee4a5a7b3712
