### ISSUE TITLE
Remove unwanted 'F' char in file system docs

### ISSUE THREAD

**Issue by allanino** [cloudwalkio/cloudwalk-docs#95]
The portuguese version of the file system page have an unwanted `F` character after the span element in this line: https://github.com/cloudwalkio/cloudwalk-docs/blob/de54e62d06bcfca5ee7dca776ef5feb98960b9ae/config/locales/pt-br.yml#L2299

**Comment by gabrielbernal** [comment]
Fixed: https://github.com/cloudwalkio/cloudwalk-docs/commit/cd6d9544aab4c67cc0e94d03eb36516306dfad5e
